### ISSUE TITLE
Название структур должно быть более понятным. 

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#1]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L9

В данном случае лучше бы подошло хотябы parametes (так как их у тебя 2) и вообще назвать Creature (существо) 
Еще возможно стоило по-отдельности сделать Hero и Dragon структуры. Так как у них если игру развить, по-разному всё выйдет, кроме здоровья и урона.

**Comment by 0verIords** [comment]
``

**Comment by 0verIords** [comment]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L10-L18

В коде добавил две таких структуры
