### ISSUE TITLE
Убрать speciesism

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#10]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L82

А про дракона в сообщениях совсем забыл. да? Попахивает спишизмом...

**Comment by 0verIords** [comment]
Добавил сообщение что дракон победил
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L60
