### ISSUE TITLE
Изменить положение счетчика

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#11]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L73

Сначала это меня удивило, но потом я вспомнил, что у тебя счетчик увеличивается в самом начале хода, еще до того как ход прошёл... Это всё равно что платить деньги кому-то прежде чем он сделает работу и не требовать от него подписи контракта. Скорее всего тебя обманут. И ты сам себя там обманываешь :) 

И вот в этой части кода ты пытаешься эту обманку "закрыть". Увеличивай счетчик только в конце хода, когда уже ясно, что игров ввел правильные данные и что ход реально прошёл. что и герой и дракон походили и т.д.

**Comment by 0verIords** [comment]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L130 теперь я честный :)
