### ISSUE TITLE
Сделать функцию валидации входных данных

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#12]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L71

Я сломал тебе игру с первой же попытки просто напечатав "аовылдаовыдла" игра три раза походила за меня, и потом я уже не хотел дальше играть. Сделай функцию которая будет валидировать ввод ползователя, чтобы ходы не совершались и статус каждый раз заново не перевыводился. И себя обезопасишь, и пользователь будет рад.

**Comment by 0verIords** [comment]
Добавил функцию проверяющий правильный ввод игрока https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L46-L52
