### ISSUE TITLE
Изменить главный цикл

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#13]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L62

порешай все тикеты, которые я отписал, и измени свой игровой цикл. НЕ понятна логика: Если пользователь введет неверные данные, уменьшить счетчик ходов, а во всех остальных случаях дать герою и дракону походить.

Пожалуйста убери эти условия и сделай нормально :) Используй continue чтобы заново спросить у игрока, что он хочет делать. Покажи ему сообщение о том, что он ошибся и можно вводить только числа от 1 до 2х . Сделай так, чтобы было очевидно, что в игре делать. 

+ Добавь пожалуйста информативности в сообщения. Сейчас за игрой очень трудно смотреть. Не понятно, кто кому какой урон на каком ходу нанёс. Что вообще происходит. и если

**Comment by 0verIords** [comment]
Добавил функцию показывающий сколько урона нанес дракон и герой https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L75-L87
Изменил игровой цикл
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L112-L136
Проверка на правильность ввода https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L124-L127
