### ISSUE TITLE
(ОПЦИОНАЛЬНО) добавить структуру Game

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#14]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L89

Перед тем как начинать игру, добавить в неё структуру Game в которой будет и счетчик ходов, и герой и дракон. и уже все методы использовать на эту структуру
`func (g Game) gameStatus()` например. Почитай про функции лучше, чтобы понять, что и как. Почему так будет эффективнее? Потому что тогда у любого метода будет доступ к дракону, герою и статусу игры, что облегчит потом и тестирование и написание самого кода. 

Можешь сначала настроить игру (задать параметры дракона, героя, счетчик на 0 поставить) а уже потом с этими параметрами начать игру в функции gameStart, где и будет логика вся и бесконечный цикл.

**Comment by 0verIords** [comment]
> Почему так будет эффективнонее?
Как я понял эффективность в элегантности и быстроте не требуют много переменных и не переполняет твой код ненужными переменными
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L20-L29
