### ISSUE TITLE
Избавиться от глобальных переменных

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#2]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L14

Их лучше использовать только тогда когда реально надо во всём пакете доступ иметь, а у тебя лучше их создавать в самой игре, а не заранее. Почитай пожалуйста про переменные по лучше. Когда локальные, когда глобальные, когда с большой буквы, когда с маленькой буквы и т.д.

**Comment by 0verIords** [comment]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L112-L117 добавил их только к функции gameRun
