### ISSUE TITLE
Сделать структуру однородной

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#3]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L11

У тебя HP паарметр с большой буквы, а damage с маленькой. В чем между ними разница? почему ты так сделал? Пожалуйста прочитай про то, как задавать параметры в структурах и на что это влияет. 

HP лучше для понятности переименовать в Health или так и написать HitPoints , так как HP могут не понять.

**Comment by anatoliyfedorenko** [comment]
https://tour.golang.org/basics/3

**Comment by 0verIords** [comment]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L10-L13 
Исправил
