### ISSUE TITLE
Убрать счетчик ходов из функции

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#4]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L23

Сейчас твоя функция статуса игры показывает статус и увеличивает счетчик. Это не хорошо, так как она делает два дела как минимум, а должна - одно. Вынеси изменение счетчика из функции.

**Comment by 0verIords** [comment]
Убрал его и сделал так https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L26-L29
