### ISSUE TITLE
Изменить входные данные и возвращать строку

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#5]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L17

Лучше чтобы функция принимала счетчик ходов, состояние здоровья героя и дракона. И возвращала строку статуса игры. Так ты её сможешь протестить лучше. Чтобы она верно подставляла параметры.

**Comment by 0verIords** [comment]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L20-L29 Сделал
