### ISSUE TITLE
Использовать fmt.Sprintf() чтобы была интерполяция

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#6]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L18

Пожалуйста избавься от кучи принтлайнов. Тебе надо строку возвращать, лучше, чтобы в этой функции она собиралась. а не выводилась на экран. Тебе руку надо набивать :)

**Comment by 0verIords** [comment]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L27-L28 исправил
