### ISSUE TITLE
Изменить функцию heroTurn

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#7]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L27

В свой ход, герой и получает от дракона, и наносит урон дракону. и лечится и т.д. Почему бы в ход героя не делать всё то, что связанно только с героем? а в ход дракона всё что связанно с драконом? 

Герой дракона атаковал, у дракона уменьшилось здоровье. Вот и весь ход. Герой лечится, у Героя увеличивается здоровье. 
Функция может принимать ответ от пользователя. А вообще на твоём месте я бы сделал по-другому. 

Написал бы две разные функции на то, как герой атакует и на то, как герой лечится. А логику спрашивать у пользователя что герой должен делать, вынес бы в цикл игры и вероятность 50% тоже вынес бы в цикл.

**Comment by 0verIords** [comment]
Функция отвечающий за ход героя:
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L75-L87 
Функции отвечающий за лечение, атаку и промахи:
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L31-L44
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L89-L104
