### ISSUE TITLE
Изменить функцию хода Дракона

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#8]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L49

Практически все комментарии из #7 актуальны и здесь. просто дракон не лечится, а это значит что нужно просто написать функцию атаки дракона в которой наносится урон Герою.

**Comment by 0verIords** [comment]
Сделал функцию атаки героя 
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L106-L110
