### ISSUE TITLE
Использовать интерполяцию

### ISSUE THREAD

**Issue by anatoliyfedorenko** [0verIords/Hero_vs_Dragon_v2#9]
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/7ab5075fea81cd873dfe681d763e1d4891d69d3b/main.go#L78

Хорошим тоном будет использование интерполяции. Так тоже можно, но это как-то не красиво. fmt.Printf тут лучше подходит

**Comment by 0verIords** [comment]
Добавил интерполяцию 
https://github.com/0verIords/Hero_vs_Dragon_v2/blob/771d33947b78f2d55e65654439ab77480c41e680/main.go#L28
